
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "./navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = localFont({
  src: "./fonts/Poppins-Regular.woff2",
  variable: "--font-poppins",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={`${poppins.variable}`}>
        <body className="font-poppins antialiased p-4 container md:mx-auto md:p-10 bg-spotify-black">
          <Navbar />
          {children}
        </body>
      </html>
  );
}